apiVersion: v1
kind: ConfigMap
metadata:
    name: mongodb-scripts
data:
  createUser.sh: |
    MONGO_INITDB_ROOT_USERNAME=$(cat "/etc/credentials/admin/MONGO_ROOT_USERNAME")
    MONGO_INITDB_ROOT_PASSWORD=$(cat "/etc/credentials/admin/MONGO_ROOT_PASSWORD")
    mongo -- "$MONGO_INITDB_DATABASE" <<EOF
      var rootUser = '$MONGO_INITDB_ROOT_USERNAME';
      var rootPassword = '$MONGO_INITDB_ROOT_PASSWORD';
      var user = '$MONGO_INITDB_USERNAME';
      var passwd = '$MONGO_INITDB_PASSWORD';

      var admin = db.getSiblingDB('admin');

      admin.auth(rootUser, rootPassword);
      db.createUser({
        user: user,
        pwd: passwd,
        roles: [
          {
            role: "readWrite",
            db: "$MONGO_INITDB_DATABASE"
          }
        ]
      });
    EOF
