apiVersion: v1
kind: PersistentVolume
metadata:
  name: common-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: common-stc
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/role
          operator: In
          values:
          - worker