apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: registry-ca
  labels:
    k8s-app: registry-ca
spec:
  selector:
    matchLabels:
      k8s-app: registry-ca
  template:
    metadata:
      labels:
        k8s-app: registry-ca
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
      - name: init-node
        command: ["nsenter"]
        args: ["--mount=/proc/1/ns/mnt", "--", "sh", "-c", "$(SETUP_SCRIPT)"]
        image: debian
        env:
        - name: TRUSTED_CERT
          valueFrom:
            secretKeyRef:
              name: registry-cert
              key: tls.crt
        - name: SETUP_SCRIPT
          valueFrom:
            configMapKeyRef:
              name: registry-script
              key: setup.sh
        securityContext:
          privileged: true
      containers:
      - name: wait
        image: k8s.gcr.io/pause:3.1