// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: catze.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Categorizer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url      string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Category string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Created  int64  `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated  int64  `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Revision string `protobuf:"bytes,6,opt,name=revision,proto3" json:"revision,omitempty"`
	Data     string `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Categorizer) Reset() {
	*x = Categorizer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catze_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Categorizer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Categorizer) ProtoMessage() {}

func (x *Categorizer) ProtoReflect() protoreflect.Message {
	mi := &file_catze_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Categorizer.ProtoReflect.Descriptor instead.
func (*Categorizer) Descriptor() ([]byte, []int) {
	return file_catze_proto_rawDescGZIP(), []int{0}
}

func (x *Categorizer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Categorizer) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Categorizer) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Categorizer) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *Categorizer) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *Categorizer) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *Categorizer) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Classifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Created  int64  `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated  int64  `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Revision string `protobuf:"bytes,6,opt,name=revision,proto3" json:"revision,omitempty"`
	Data     string `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Classifier) Reset() {
	*x = Classifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catze_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Classifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Classifier) ProtoMessage() {}

func (x *Classifier) ProtoReflect() protoreflect.Message {
	mi := &file_catze_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Classifier.ProtoReflect.Descriptor instead.
func (*Classifier) Descriptor() ([]byte, []int) {
	return file_catze_proto_rawDescGZIP(), []int{1}
}

func (x *Classifier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Classifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Classifier) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Classifier) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *Classifier) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *Classifier) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *Classifier) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type CategorizeURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Data   string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Cmodel string `protobuf:"bytes,3,opt,name=cmodel,proto3" json:"cmodel,omitempty"`
}

func (x *CategorizeURLRequest) Reset() {
	*x = CategorizeURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catze_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategorizeURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorizeURLRequest) ProtoMessage() {}

func (x *CategorizeURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catze_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorizeURLRequest.ProtoReflect.Descriptor instead.
func (*CategorizeURLRequest) Descriptor() ([]byte, []int) {
	return file_catze_proto_rawDescGZIP(), []int{2}
}

func (x *CategorizeURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CategorizeURLRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *CategorizeURLRequest) GetCmodel() string {
	if x != nil {
		return x.Cmodel
	}
	return ""
}

type CategorizeURLsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []*CategorizeURLRequest `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *CategorizeURLsRequest) Reset() {
	*x = CategorizeURLsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catze_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategorizeURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorizeURLsRequest) ProtoMessage() {}

func (x *CategorizeURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catze_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorizeURLsRequest.ProtoReflect.Descriptor instead.
func (*CategorizeURLsRequest) Descriptor() ([]byte, []int) {
	return file_catze_proto_rawDescGZIP(), []int{3}
}

func (x *CategorizeURLsRequest) GetUrls() []*CategorizeURLRequest {
	if x != nil {
		return x.Urls
	}
	return nil
}

type CategorizeURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url      string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *CategorizeURLResponse) Reset() {
	*x = CategorizeURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catze_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategorizeURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorizeURLResponse) ProtoMessage() {}

func (x *CategorizeURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catze_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorizeURLResponse.ProtoReflect.Descriptor instead.
func (*CategorizeURLResponse) Descriptor() ([]byte, []int) {
	return file_catze_proto_rawDescGZIP(), []int{4}
}

func (x *CategorizeURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CategorizeURLResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ClassificationModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Class string `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	Data  string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ClassificationModel) Reset() {
	*x = ClassificationModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catze_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassificationModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationModel) ProtoMessage() {}

func (x *ClassificationModel) ProtoReflect() protoreflect.Message {
	mi := &file_catze_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationModel.ProtoReflect.Descriptor instead.
func (*ClassificationModel) Descriptor() ([]byte, []int) {
	return file_catze_proto_rawDescGZIP(), []int{5}
}

func (x *ClassificationModel) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *ClassificationModel) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GenerateClassificationModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Model    []*ClassificationModel `protobuf:"bytes,2,rep,name=model,proto3" json:"model,omitempty"`
}

func (x *GenerateClassificationModelRequest) Reset() {
	*x = GenerateClassificationModelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catze_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateClassificationModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateClassificationModelRequest) ProtoMessage() {}

func (x *GenerateClassificationModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catze_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateClassificationModelRequest.ProtoReflect.Descriptor instead.
func (*GenerateClassificationModelRequest) Descriptor() ([]byte, []int) {
	return file_catze_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateClassificationModelRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GenerateClassificationModelRequest) GetModel() []*ClassificationModel {
	if x != nil {
		return x.Model
	}
	return nil
}

type GetClassificationModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetClassificationModelRequest) Reset() {
	*x = GetClassificationModelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catze_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClassificationModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassificationModelRequest) ProtoMessage() {}

func (x *GetClassificationModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catze_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassificationModelRequest.ProtoReflect.Descriptor instead.
func (*GetClassificationModelRequest) Descriptor() ([]byte, []int) {
	return file_catze_proto_rawDescGZIP(), []int{7}
}

func (x *GetClassificationModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateClassificationModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *UpdateClassificationModelRequest) Reset() {
	*x = UpdateClassificationModelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catze_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateClassificationModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClassificationModelRequest) ProtoMessage() {}

func (x *UpdateClassificationModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catze_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClassificationModelRequest.ProtoReflect.Descriptor instead.
func (*UpdateClassificationModelRequest) Descriptor() ([]byte, []int) {
	return file_catze_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateClassificationModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateClassificationModelRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type DeleteClassificationModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeleteClassificationModelRequest) Reset() {
	*x = DeleteClassificationModelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catze_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteClassificationModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClassificationModelRequest) ProtoMessage() {}

func (x *DeleteClassificationModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catze_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClassificationModelRequest.ProtoReflect.Descriptor instead.
func (*DeleteClassificationModelRequest) Descriptor() ([]byte, []int) {
	return file_catze_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteClassificationModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteClassificationModelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeleteClassificationModelResponse) Reset() {
	*x = DeleteClassificationModelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catze_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteClassificationModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClassificationModelResponse) ProtoMessage() {}

func (x *DeleteClassificationModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catze_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClassificationModelResponse.ProtoReflect.Descriptor instead.
func (*DeleteClassificationModelResponse) Descriptor() ([]byte, []int) {
	return file_catze_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteClassificationModelResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteClassificationModelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *DeleteClassificationModelsRequest) Reset() {
	*x = DeleteClassificationModelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catze_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteClassificationModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClassificationModelsRequest) ProtoMessage() {}

func (x *DeleteClassificationModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catze_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClassificationModelsRequest.ProtoReflect.Descriptor instead.
func (*DeleteClassificationModelsRequest) Descriptor() ([]byte, []int) {
	return file_catze_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteClassificationModelsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type ListClassificationModelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Categories []string `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Count      string   `protobuf:"bytes,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ListClassificationModelsRequest) Reset() {
	*x = ListClassificationModelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catze_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListClassificationModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClassificationModelsRequest) ProtoMessage() {}

func (x *ListClassificationModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catze_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClassificationModelsRequest.ProtoReflect.Descriptor instead.
func (*ListClassificationModelsRequest) Descriptor() ([]byte, []int) {
	return file_catze_proto_rawDescGZIP(), []int{12}
}

func (x *ListClassificationModelsRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ListClassificationModelsRequest) GetCount() string {
	if x != nil {
		return x.Count
	}
	return ""
}

var File_catze_proto protoreflect.FileDescriptor

var file_catze_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x61, 0x74, 0x7a, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0xaf, 0x01, 0x0a, 0x0b, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x7a, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0xb0, 0x01, 0x0a, 0x0a, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x54, 0x0a, 0x14, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x7a, 0x65, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x45, 0x0a, 0x15,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x7a, 0x65, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x75,
	0x72, 0x6c, 0x73, 0x22, 0x45, 0x0a, 0x15, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x7a,
	0x65, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x3f, 0x0a, 0x13, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6f, 0x0a, 0x22, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x2d, 0x0a,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x33, 0x0a, 0x1d,
	0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x52, 0x0a, 0x20, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x36, 0x0a, 0x20, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a,
	0x21, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x21, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x22, 0x57, 0x0a, 0x1f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xc0, 0x05, 0x0a, 0x0c, 0x43,
	0x61, 0x74, 0x7a, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0d, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x55, 0x52, 0x4c, 0x12, 0x18, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x55, 0x52, 0x4c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x48, 0x0a, 0x0e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x55,
	0x52, 0x4c, 0x73, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x7a, 0x65, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x55, 0x52,
	0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x55, 0x0a, 0x1b, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x26, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x12, 0x4b, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x21, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12,
	0x51, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x24, 0x2e, 0x70,
	0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x12, 0x68, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x24, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6c, 0x0a, 0x1a,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x12, 0x25, 0x2e, 0x70, 0x62, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x51, 0x0a, 0x18, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x12, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x72, 0x30, 0x01, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_catze_proto_rawDescOnce sync.Once
	file_catze_proto_rawDescData = file_catze_proto_rawDesc
)

func file_catze_proto_rawDescGZIP() []byte {
	file_catze_proto_rawDescOnce.Do(func() {
		file_catze_proto_rawDescData = protoimpl.X.CompressGZIP(file_catze_proto_rawDescData)
	})
	return file_catze_proto_rawDescData
}

var file_catze_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_catze_proto_goTypes = []interface{}{
	(*Categorizer)(nil),                        // 0: pb.Categorizer
	(*Classifier)(nil),                         // 1: pb.Classifier
	(*CategorizeURLRequest)(nil),               // 2: pb.CategorizeURLRequest
	(*CategorizeURLsRequest)(nil),              // 3: pb.CategorizeURLsRequest
	(*CategorizeURLResponse)(nil),              // 4: pb.CategorizeURLResponse
	(*ClassificationModel)(nil),                // 5: pb.ClassificationModel
	(*GenerateClassificationModelRequest)(nil), // 6: pb.GenerateClassificationModelRequest
	(*GetClassificationModelRequest)(nil),      // 7: pb.GetClassificationModelRequest
	(*UpdateClassificationModelRequest)(nil),   // 8: pb.UpdateClassificationModelRequest
	(*DeleteClassificationModelRequest)(nil),   // 9: pb.DeleteClassificationModelRequest
	(*DeleteClassificationModelResponse)(nil),  // 10: pb.DeleteClassificationModelResponse
	(*DeleteClassificationModelsRequest)(nil),  // 11: pb.DeleteClassificationModelsRequest
	(*ListClassificationModelsRequest)(nil),    // 12: pb.ListClassificationModelsRequest
}
var file_catze_proto_depIdxs = []int32{
	2,  // 0: pb.CategorizeURLsRequest.urls:type_name -> pb.CategorizeURLRequest
	5,  // 1: pb.GenerateClassificationModelRequest.model:type_name -> pb.ClassificationModel
	2,  // 2: pb.CatzeService.CategorizeURL:input_type -> pb.CategorizeURLRequest
	3,  // 3: pb.CatzeService.CategorizeURLs:input_type -> pb.CategorizeURLsRequest
	6,  // 4: pb.CatzeService.GenerateClassificationModel:input_type -> pb.GenerateClassificationModelRequest
	7,  // 5: pb.CatzeService.GetClassificationModel:input_type -> pb.GetClassificationModelRequest
	8,  // 6: pb.CatzeService.UpdateClassificationModel:input_type -> pb.UpdateClassificationModelRequest
	9,  // 7: pb.CatzeService.DeleteClassificationModel:input_type -> pb.DeleteClassificationModelRequest
	11, // 8: pb.CatzeService.DeleteClassificationModels:input_type -> pb.DeleteClassificationModelsRequest
	12, // 9: pb.CatzeService.ListClassificationModels:input_type -> pb.ListClassificationModelsRequest
	4,  // 10: pb.CatzeService.CategorizeURL:output_type -> pb.CategorizeURLResponse
	4,  // 11: pb.CatzeService.CategorizeURLs:output_type -> pb.CategorizeURLResponse
	1,  // 12: pb.CatzeService.GenerateClassificationModel:output_type -> pb.Classifier
	1,  // 13: pb.CatzeService.GetClassificationModel:output_type -> pb.Classifier
	1,  // 14: pb.CatzeService.UpdateClassificationModel:output_type -> pb.Classifier
	10, // 15: pb.CatzeService.DeleteClassificationModel:output_type -> pb.DeleteClassificationModelResponse
	10, // 16: pb.CatzeService.DeleteClassificationModels:output_type -> pb.DeleteClassificationModelResponse
	1,  // 17: pb.CatzeService.ListClassificationModels:output_type -> pb.Classifier
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_catze_proto_init() }
func file_catze_proto_init() {
	if File_catze_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_catze_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Categorizer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catze_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Classifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catze_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategorizeURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catze_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategorizeURLsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catze_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategorizeURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catze_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassificationModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catze_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateClassificationModelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catze_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClassificationModelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catze_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateClassificationModelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catze_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteClassificationModelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catze_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteClassificationModelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catze_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteClassificationModelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catze_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListClassificationModelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_catze_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catze_proto_goTypes,
		DependencyIndexes: file_catze_proto_depIdxs,
		MessageInfos:      file_catze_proto_msgTypes,
	}.Build()
	File_catze_proto = out.File
	file_catze_proto_rawDesc = nil
	file_catze_proto_goTypes = nil
	file_catze_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CatzeServiceClient is the client API for CatzeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CatzeServiceClient interface {
	CategorizeURL(ctx context.Context, in *CategorizeURLRequest, opts ...grpc.CallOption) (*CategorizeURLResponse, error)
	CategorizeURLs(ctx context.Context, in *CategorizeURLsRequest, opts ...grpc.CallOption) (CatzeService_CategorizeURLsClient, error)
	GenerateClassificationModel(ctx context.Context, in *GenerateClassificationModelRequest, opts ...grpc.CallOption) (*Classifier, error)
	GetClassificationModel(ctx context.Context, in *GetClassificationModelRequest, opts ...grpc.CallOption) (*Classifier, error)
	UpdateClassificationModel(ctx context.Context, in *UpdateClassificationModelRequest, opts ...grpc.CallOption) (*Classifier, error)
	DeleteClassificationModel(ctx context.Context, in *DeleteClassificationModelRequest, opts ...grpc.CallOption) (*DeleteClassificationModelResponse, error)
	DeleteClassificationModels(ctx context.Context, in *DeleteClassificationModelsRequest, opts ...grpc.CallOption) (CatzeService_DeleteClassificationModelsClient, error)
	ListClassificationModels(ctx context.Context, in *ListClassificationModelsRequest, opts ...grpc.CallOption) (CatzeService_ListClassificationModelsClient, error)
}

type catzeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatzeServiceClient(cc grpc.ClientConnInterface) CatzeServiceClient {
	return &catzeServiceClient{cc}
}

func (c *catzeServiceClient) CategorizeURL(ctx context.Context, in *CategorizeURLRequest, opts ...grpc.CallOption) (*CategorizeURLResponse, error) {
	out := new(CategorizeURLResponse)
	err := c.cc.Invoke(ctx, "/pb.CatzeService/CategorizeURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catzeServiceClient) CategorizeURLs(ctx context.Context, in *CategorizeURLsRequest, opts ...grpc.CallOption) (CatzeService_CategorizeURLsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CatzeService_serviceDesc.Streams[0], "/pb.CatzeService/CategorizeURLs", opts...)
	if err != nil {
		return nil, err
	}
	x := &catzeServiceCategorizeURLsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CatzeService_CategorizeURLsClient interface {
	Recv() (*CategorizeURLResponse, error)
	grpc.ClientStream
}

type catzeServiceCategorizeURLsClient struct {
	grpc.ClientStream
}

func (x *catzeServiceCategorizeURLsClient) Recv() (*CategorizeURLResponse, error) {
	m := new(CategorizeURLResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *catzeServiceClient) GenerateClassificationModel(ctx context.Context, in *GenerateClassificationModelRequest, opts ...grpc.CallOption) (*Classifier, error) {
	out := new(Classifier)
	err := c.cc.Invoke(ctx, "/pb.CatzeService/GenerateClassificationModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catzeServiceClient) GetClassificationModel(ctx context.Context, in *GetClassificationModelRequest, opts ...grpc.CallOption) (*Classifier, error) {
	out := new(Classifier)
	err := c.cc.Invoke(ctx, "/pb.CatzeService/GetClassificationModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catzeServiceClient) UpdateClassificationModel(ctx context.Context, in *UpdateClassificationModelRequest, opts ...grpc.CallOption) (*Classifier, error) {
	out := new(Classifier)
	err := c.cc.Invoke(ctx, "/pb.CatzeService/UpdateClassificationModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catzeServiceClient) DeleteClassificationModel(ctx context.Context, in *DeleteClassificationModelRequest, opts ...grpc.CallOption) (*DeleteClassificationModelResponse, error) {
	out := new(DeleteClassificationModelResponse)
	err := c.cc.Invoke(ctx, "/pb.CatzeService/DeleteClassificationModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catzeServiceClient) DeleteClassificationModels(ctx context.Context, in *DeleteClassificationModelsRequest, opts ...grpc.CallOption) (CatzeService_DeleteClassificationModelsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CatzeService_serviceDesc.Streams[1], "/pb.CatzeService/DeleteClassificationModels", opts...)
	if err != nil {
		return nil, err
	}
	x := &catzeServiceDeleteClassificationModelsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CatzeService_DeleteClassificationModelsClient interface {
	Recv() (*DeleteClassificationModelResponse, error)
	grpc.ClientStream
}

type catzeServiceDeleteClassificationModelsClient struct {
	grpc.ClientStream
}

func (x *catzeServiceDeleteClassificationModelsClient) Recv() (*DeleteClassificationModelResponse, error) {
	m := new(DeleteClassificationModelResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *catzeServiceClient) ListClassificationModels(ctx context.Context, in *ListClassificationModelsRequest, opts ...grpc.CallOption) (CatzeService_ListClassificationModelsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CatzeService_serviceDesc.Streams[2], "/pb.CatzeService/ListClassificationModels", opts...)
	if err != nil {
		return nil, err
	}
	x := &catzeServiceListClassificationModelsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CatzeService_ListClassificationModelsClient interface {
	Recv() (*Classifier, error)
	grpc.ClientStream
}

type catzeServiceListClassificationModelsClient struct {
	grpc.ClientStream
}

func (x *catzeServiceListClassificationModelsClient) Recv() (*Classifier, error) {
	m := new(Classifier)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CatzeServiceServer is the server API for CatzeService service.
type CatzeServiceServer interface {
	CategorizeURL(context.Context, *CategorizeURLRequest) (*CategorizeURLResponse, error)
	CategorizeURLs(*CategorizeURLsRequest, CatzeService_CategorizeURLsServer) error
	GenerateClassificationModel(context.Context, *GenerateClassificationModelRequest) (*Classifier, error)
	GetClassificationModel(context.Context, *GetClassificationModelRequest) (*Classifier, error)
	UpdateClassificationModel(context.Context, *UpdateClassificationModelRequest) (*Classifier, error)
	DeleteClassificationModel(context.Context, *DeleteClassificationModelRequest) (*DeleteClassificationModelResponse, error)
	DeleteClassificationModels(*DeleteClassificationModelsRequest, CatzeService_DeleteClassificationModelsServer) error
	ListClassificationModels(*ListClassificationModelsRequest, CatzeService_ListClassificationModelsServer) error
}

// UnimplementedCatzeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCatzeServiceServer struct {
}

func (*UnimplementedCatzeServiceServer) CategorizeURL(context.Context, *CategorizeURLRequest) (*CategorizeURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CategorizeURL not implemented")
}
func (*UnimplementedCatzeServiceServer) CategorizeURLs(*CategorizeURLsRequest, CatzeService_CategorizeURLsServer) error {
	return status.Errorf(codes.Unimplemented, "method CategorizeURLs not implemented")
}
func (*UnimplementedCatzeServiceServer) GenerateClassificationModel(context.Context, *GenerateClassificationModelRequest) (*Classifier, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateClassificationModel not implemented")
}
func (*UnimplementedCatzeServiceServer) GetClassificationModel(context.Context, *GetClassificationModelRequest) (*Classifier, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClassificationModel not implemented")
}
func (*UnimplementedCatzeServiceServer) UpdateClassificationModel(context.Context, *UpdateClassificationModelRequest) (*Classifier, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClassificationModel not implemented")
}
func (*UnimplementedCatzeServiceServer) DeleteClassificationModel(context.Context, *DeleteClassificationModelRequest) (*DeleteClassificationModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteClassificationModel not implemented")
}
func (*UnimplementedCatzeServiceServer) DeleteClassificationModels(*DeleteClassificationModelsRequest, CatzeService_DeleteClassificationModelsServer) error {
	return status.Errorf(codes.Unimplemented, "method DeleteClassificationModels not implemented")
}
func (*UnimplementedCatzeServiceServer) ListClassificationModels(*ListClassificationModelsRequest, CatzeService_ListClassificationModelsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListClassificationModels not implemented")
}

func RegisterCatzeServiceServer(s *grpc.Server, srv CatzeServiceServer) {
	s.RegisterService(&_CatzeService_serviceDesc, srv)
}

func _CatzeService_CategorizeURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategorizeURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatzeServiceServer).CategorizeURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CatzeService/CategorizeURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatzeServiceServer).CategorizeURL(ctx, req.(*CategorizeURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatzeService_CategorizeURLs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CategorizeURLsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatzeServiceServer).CategorizeURLs(m, &catzeServiceCategorizeURLsServer{stream})
}

type CatzeService_CategorizeURLsServer interface {
	Send(*CategorizeURLResponse) error
	grpc.ServerStream
}

type catzeServiceCategorizeURLsServer struct {
	grpc.ServerStream
}

func (x *catzeServiceCategorizeURLsServer) Send(m *CategorizeURLResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CatzeService_GenerateClassificationModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateClassificationModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatzeServiceServer).GenerateClassificationModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CatzeService/GenerateClassificationModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatzeServiceServer).GenerateClassificationModel(ctx, req.(*GenerateClassificationModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatzeService_GetClassificationModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClassificationModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatzeServiceServer).GetClassificationModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CatzeService/GetClassificationModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatzeServiceServer).GetClassificationModel(ctx, req.(*GetClassificationModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatzeService_UpdateClassificationModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClassificationModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatzeServiceServer).UpdateClassificationModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CatzeService/UpdateClassificationModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatzeServiceServer).UpdateClassificationModel(ctx, req.(*UpdateClassificationModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatzeService_DeleteClassificationModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClassificationModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatzeServiceServer).DeleteClassificationModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CatzeService/DeleteClassificationModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatzeServiceServer).DeleteClassificationModel(ctx, req.(*DeleteClassificationModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatzeService_DeleteClassificationModels_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeleteClassificationModelsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatzeServiceServer).DeleteClassificationModels(m, &catzeServiceDeleteClassificationModelsServer{stream})
}

type CatzeService_DeleteClassificationModelsServer interface {
	Send(*DeleteClassificationModelResponse) error
	grpc.ServerStream
}

type catzeServiceDeleteClassificationModelsServer struct {
	grpc.ServerStream
}

func (x *catzeServiceDeleteClassificationModelsServer) Send(m *DeleteClassificationModelResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CatzeService_ListClassificationModels_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListClassificationModelsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatzeServiceServer).ListClassificationModels(m, &catzeServiceListClassificationModelsServer{stream})
}

type CatzeService_ListClassificationModelsServer interface {
	Send(*Classifier) error
	grpc.ServerStream
}

type catzeServiceListClassificationModelsServer struct {
	grpc.ServerStream
}

func (x *catzeServiceListClassificationModelsServer) Send(m *Classifier) error {
	return x.ServerStream.SendMsg(m)
}

var _CatzeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CatzeService",
	HandlerType: (*CatzeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CategorizeURL",
			Handler:    _CatzeService_CategorizeURL_Handler,
		},
		{
			MethodName: "GenerateClassificationModel",
			Handler:    _CatzeService_GenerateClassificationModel_Handler,
		},
		{
			MethodName: "GetClassificationModel",
			Handler:    _CatzeService_GetClassificationModel_Handler,
		},
		{
			MethodName: "UpdateClassificationModel",
			Handler:    _CatzeService_UpdateClassificationModel_Handler,
		},
		{
			MethodName: "DeleteClassificationModel",
			Handler:    _CatzeService_DeleteClassificationModel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CategorizeURLs",
			Handler:       _CatzeService_CategorizeURLs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DeleteClassificationModels",
			Handler:       _CatzeService_DeleteClassificationModels_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListClassificationModels",
			Handler:       _CatzeService_ListClassificationModels_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "catze.proto",
}
