apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc
      role: auth
  template:
    metadata:
      labels:
        app: svc
        role: auth
    spec:
      containers:
      - name: auth-svc
        image: mtnmunuklu/lescatit:v0.1.0
        ports:
        - containerPort: 9001
        command:
          - sh
          - -c
          - /app/authsvc -local=false
        env:
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: svc-secrets
                key: dbUser
          - name: DATABASE_PASS
            valueFrom:
              secretKeyRef:
                name: svc-secrets
                key: dbPass
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: svc-secrets
                key: jwtSecretKey

          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: svc-configs
                key: dbHost
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: svc-configs
                key: dbPort
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: svc-configs
                key: dbName
          - name: CERT_PATH
            valueFrom:
              configMapKeyRef:
                name: svc-configs
                key: certPath
        volumeMounts:
        - name: service-certs
          mountPath: /etc/certs
          readOnly: true
      volumes:
      - name: service-certs
        secret:
          secretName: service-cert
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: svc
    role: auth