apiVersion: apps/v1
kind: Deployment
metadata:
  name: catze-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc
      role: catze
  template:
    metadata:
      labels:
        app: svc
        role: catze
    spec:
      nodeSelector:
        kubernetes.io/role: worker
      containers:
      - name: catze-svc
        image: mtnmunuklu/lescatit:v1.0.0
        ports:
        - containerPort: 9003
        command:
          - sh
          - -c
          - /app/catzesvc -local=false
        env:
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: svc-secrets
                key: dbUser
          - name: DATABASE_PASS
            valueFrom:
              secretKeyRef:
                name: svc-secrets
                key: dbPass

          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: svc-configs
                key: dbHost
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: svc-configs
                key: dbPort
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: svc-configs
                key: dbName
          - name: CERT_PATH
            valueFrom:
              configMapKeyRef:
                name: svc-configs
                key: certPath
        volumeMounts:
        - name: service-certs
          mountPath: /etc/certs
          readOnly: true
      volumes:
      - name: service-certs
        secret:
          secretName: service-certs
---
apiVersion: v1
kind: Service
metadata:
  name: catze-service
spec:
  ports:
    - protocol: TCP
      port: 9004
      targetPort: 9004
  selector:
    app: svc
    role: catze