apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: svc
      role: api
  template:
    metadata:
      labels:
        app: svc
        role: api
    spec:
      containers:
      - name: api-svc
        image: cws:v1
        ports:
        - containerPort: 9000
        command:
        - sh
        - -c
        - /app/apisvc -auth_addr=$auth_addr -crawl_addr=$crawl_addr -catze_addr=$catze_addr -cat_addr=$cat_addr
        env:
          - name: auth_addr
            value: auth-service:9001
          - name: crawl_addr
            value: crawl-service:9003
          - name: catze_addr
            value: catze-service:9004
          - name: cat_addr
            value: cat-service:9002
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: svc-secrets
                key: JwtSecretKey
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: svc
    role: api
