apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc
      role: cat
  template:
    metadata:
      labels:
        app: svc
        role: cat
    spec:
      containers:
      - name: cat-svc
        image: cws:v1
        ports:
        - containerPort: 9002
        command:
          - sh
          - -c
          - /app/catsvc -local=false
        env:
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: svc-secrets
                key: dbUser
          - name: DATABASE_PASS
            valueFrom:
              secretKeyRef:
                name: svc-secrets
                key: dbPass
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: svc-secrets
                key: JwtSecretKey

          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: svc-configs
                key: db_host
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: svc-configs
                key: db_port
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: svc-configs
                key: db_name
---
apiVersion: v1
kind: Service
metadata:
  name: cat-service
spec:
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  selector:
    app: svc
    role: cat