apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawl-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc
      role: crawl
  template:
    metadata:
      labels:
        app: svc
        role: crawl
    spec:
      containers:
      - name: crawl-svc
        image: lescatit:v1
        ports:
        - containerPort: 9003
        command:
          - sh
          - -c
          - /app/crawlsvc -local=false
        env:
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: svc-secrets
                key: dbUser
          - name: DATABASE_PASS
            valueFrom:
              secretKeyRef:
                name: svc-secrets
                key: dbPass
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: svc-secrets
                key: jwtSecretKey

          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: svc-configs
                key: dbHost
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: svc-configs
                key: dbPort
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: svc-configs
                key: dbName
          - name: CERT_PATH
            valueFrom:
              configMapKeyRef:
                name: svc-configs
                key: certPath
        volumeMounts:
        - name: certs
          mountPath: /etc/certs
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: cert-secret
---
apiVersion: v1
kind: Service
metadata:
  name: crawl-service
spec:
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003
  selector:
    app: svc
    role: crawl