name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.go'

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go-version:
          - 1.19

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build for ${{ matrix.platform }}
        run: go build -v ./...

      - name: Test
        run: go test -v ./...